version: '3.8'
services:
  docker_redis:
    image: redis:7.2.3
    restart: always
    ports:
      - '6679:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwamDxKPfDmwMtyKVge8oLa2t19
    volumes: 
      - ./data_redis:/data