version: '3.1'

services:
  docker_mysql:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    ports:
      - 3606:3306
    environment:
      MYSQL_ROOT_PASSWORD: sGoY52RGHVooGEKk9ftpag3kPG6XRtyO
      MYSQL_DATABASE: mydb1
      MYSQL_USER: user01
      MYSQL_PASSWORD: 123456789
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./data_msyql:/var/lib/mysql